# Results

```{r}
#This is how to load json files 
library(jsonlite)
library(tidyverse)
grenades <- jsonlite::fromJSON("code/data/ALL_grenades.json", simplifyVector = TRUE)
kills <- jsonlite::fromJSON("code/data/ALL_kills.json", simplifyVector = TRUE)
damages <- jsonlite::fromJSON("code/data/ALL_damages.json", simplifyVector = TRUE)
flashes <- jsonlite::fromJSON("code/data/ALL_flashes.json", simplifyVector = TRUE)
```





```{r}
#This is wheree we store the final score of each match
wins <- kills %>% group_by(match_id) %>% summarise(round_tot=last(round_tot)+1,team1=last(match_team1),team2=last(match_team2),winner=last(round_won_by),looser=if_else(last(round_won_by)!=last(match_team1),last(match_team1),last(team2)))

#final score formula takes into account overtime. An overtime can last up to 6 rounds before another overtime occurs

wins <- wins %>%  mutate(final_score_winner=if_else(round_tot<31,16, 19+3*(  (round_tot-31)%/%6))) %>%  mutate(final_score_looser=round_tot-final_score_winner) %>% mutate(score_diff=(final_score_winner-final_score_looser)/round_tot)

```

```{r}
#team stats on kills
team_kills <- kills %>% filter(attackerTeam!=victimTeam) %>%  group_by(match_id,attackerTeam) %>% summarise(kills_tot=n(),kpr=n()/last(round_tot),team=last(attackerTeam),hs_percent= sum(isHeadshot==TRUE)/n(),blinded_percent=sum(attackerBlinded==TRUE)/n(),blinded_percent=sum(victimBlinded==TRUE)/n(),first_kill_percent=sum(isFirstKill==TRUE)/last(round_tot),first_kill_percent=sum(isFirstKill==TRUE)/last(round_tot),non_traded_percent=sum(isTrade==FALSE)/n(),assist_percent= sum(!is.na(assisterTeam))/last(round_tot))



#team stats on  damages
team_damages <- damages %>% filter(attackerTeam!=victimTeam) %>%  group_by(match_id,attackerTeam) %>% summarise(adr=sum(hpDamageTaken)/last(round_tot),team=last(attackerTeam),strafing=sum(attackerStrafe==TRUE)/n())

#team stat on flash 

team_flashes <- flashes %>% filter(attackerTeam!=playerTeam) %>%  group_by(match_id,attackerTeam) %>% summarise(avg_flash_duration=sum(flashDuration)/last(round_tot),team=last(attackerTeam))

#team stats for grenades
team_grenades <- grenades  %>% rename(attackerTeam=throwerTeam) %>%   group_by(match_id,attackerTeam) %>% summarise(grenades_per_round=n()/last(round_tot),team=last(attackerTeam),smokes_per_round=sum("Smoke Grenade"==grenadeType)/last(round_tot),attack_grenades_round=sum("Smoke Grenade"!=grenadeType)/last(round_tot),event=last(match_event))

#join everything
team_killsstat <- inner_join(team_kills,wins) %>% inner_join(team_damages) %>% inner_join(team_flashes) %>%  inner_join(team_grenades)  


#create y axis score difference data
team_killsstat <- team_killsstat %>% mutate(relative_score_diff=if_else(winner!=attackerTeam,-score_diff,score_diff))



library(reshape2)
library(forcats)
df.mlt <- melt(team_killsstat,  variable.name="var",id.vars=c("relative_score_diff","score_diff","match_id","attackerTeam","kills_tot","team","winner","looser","final_score_winner","final_score_looser","team1","team2","round_tot","event"))
df.mlt <- df.mlt %>% mutate(yvalue=as.double(value)) 
df.mlt <-  df.mlt %>% group_by(var) %>% 
    mutate(pvalue= cor(yvalue, relative_score_diff)) %>% ungroup() %>% mutate(label_names=paste(as.character(var),strtrim(as.character(pvalue), 5)), sep = " ", collapse = NULL) %>% mutate(label_names=fct_reorder(label_names, -pvalue))


mylabeller <- function(variable,value){
  return(cor_tests[value])
}

df.mlt %>% ggplot(aes(x=yvalue, y=relative_score_diff))+
  #geom_smooth(method = "lm", se = FALSE) +
  geom_point(size = .15) +
  geom_smooth(method='lm', formula = y~x, colour='red')+
  #geom_text(, aes(x = 3, y = 0, label = paste(" ",pvalue), family = "serif"), color = 'blue',  parse = TRUE)+
  facet_wrap(~label_names, scales = "free") +
  xlab("Team stat") +
  ylab("relative score diff") +
  ylim(-2, 4)+
  theme_linedraw()

#id.vars=c("kpr", "hs_percent","blinded_percent","first_kill_percent","trade_percent")

```
```{r}
# new stat generation

fit <- lm(relative_score_diff ~ kpr + adr + first_kill_percent + grenades_per_round + attack_grenades_round + smokes_per_round + assist_percent + non_traded_percent + avg_flash_duration, data=team_killsstat)
summary(fit)

coef <- coefficients(fit)

team_killsstat <- team_killsstat %>% mutate(rating=100*(coef[1]+kpr*coef[2]+adr*coef[3]+first_kill_percent*coef[4]+grenades_per_round *coef[5]+attack_grenades_round*coef[6]+assist_percent*coef[8]+non_traded_percent*coef[9]+avg_flash_duration *coef[10])) %>%  mutate(rating=100*(rating-min(rating))/(max(rating)-min(rating)))

```
Top teams for each event

```{r  fig.height=8}
top_teams <- team_killsstat %>% group_by(team,event) %>% summarize(rating=mean(rating)) %>% filter( !is.nan(rating) ,rating!=0) 


level_order <- c('DreamHack Winter 2013','EMS One Katowice 2014','ESL One Cologne 2014','DreamHack Winter 2014','ESL One Katowice 2015','ESL One Cologne 2015','DreamHack Open Cluj-Napoca 2015','MLG Columbus 2016','ESL One Cologne 2016','ELEAGUE Major 2017','PGL Major Krakow 2017','ELEAGUE Major 2018','FACEIT Major 2018','IEM Katowice 2019','StarLadder Major Berlin 2019')
top_teams <- top_teams %>% mutate(winner= (team=="Fnatic" & event=="ESL One Cologne 2015")| (team=="Team EnVyUs" & event=="DreamHack Open Cluj-Napoca 2015") |  (team=="Luminosity Gaming" & event=="MLG Columbus 2016") | (team=="SK Gaming" & event=="ESL One Cologne 2016") | (team=="Gambit Gaming" & event=="PGL Major Krakow 2017") |(team=="Cloud9" & event=="ELEAGUE Major 2018") | ((team=='Astralis')&(event %in% c("StarLadder Major Berlin 2019","FACEIT Major 2018","IEM Katowice 2019","ELEAGUE Major 2017"))))



reorder_within <- function(x, by, within, fun = mean, sep = "___", ...) {
  new_x <- paste(x, within, sep = sep)
  stats::reorder(new_x, by, FUN = fun)
}
scale_x_reordered <- function(..., sep = "___") {
  reg <- paste0(sep, ".+$")
  ggplot2::scale_x_discrete(labels = function(x) gsub(reg, "", x), ...)
}

ggplot(data=top_teams, aes(x=reorder_within(team,-rating,event), y=rating,color=winner)) +
facet_wrap(~factor(event,levels=level_order), scales = "free") +
scale_x_reordered() +
geom_bar(stat="identity")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



```{r}
#all time player stats
player_kills <- kills %>% filter(attackerTeam!=victimTeam) %>%  group_by(match_id,attackerSteamID) %>% summarise(kills_tot=n(),kpr=n()/last(round_tot),team=last(attackerTeam),hs_percent= sum(isHeadshot==TRUE)/n(),blinded_percent=sum(attackerBlinded==TRUE)/n(),blinded_percent=sum(victimBlinded==TRUE)/n(),first_kill_percent=sum(isFirstKill==TRUE)/last(round_tot),first_kill_percent=sum(isFirstKill==TRUE)/last(round_tot),non_traded_percent=sum(isTrade==FALSE)/n(),assist_percent= sum(!is.na(assisterTeam))/last(round_tot))

#player stats on  damages
player_damages <- damages %>% filter(attackerTeam!=victimTeam) %>%  group_by(match_id,attackerSteamID) %>% summarise(adr=sum(hpDamageTaken)/last(round_tot),team=last(attackerTeam),strafing=sum(attackerStrafe==TRUE)/n())

#player stat on flash 

player_flashes <- flashes %>% filter(attackerTeam!=playerTeam) %>%  group_by(match_id,attackerSteamID) %>% summarise(avg_flash_duration=sum(flashDuration)/last(round_tot),team=last(attackerTeam))

#player stats for grenades

player_grenades <- grenades  %>% rename(attackerSteamID=throwerSteamID) %>%   group_by(match_id,attackerSteamID) %>% summarise(grenades_per_round=n()/last(round_tot),smokes_per_round=sum("Smoke Grenade"==grenadeType)/last(round_tot),attack_grenades_round=sum("Smoke Grenade"!=grenadeType)/last(round_tot),name=last(throwerName),event=last(match_event),date=last(match_date))

#join everything
playerstat <- player_kills %>% inner_join(player_damages) %>% inner_join(player_flashes) %>%  inner_join(player_grenades)  %>% mutate(rating=100*(coef[1]+kpr*coef[2]+adr*coef[3]+first_kill_percent*coef[4]+grenades_per_round *coef[5]+attack_grenades_round*coef[6]+assist_percent*coef[8]+non_traded_percent*coef[9]+avg_flash_duration *coef[10]))


playerstat <- playerstat %>% mutate(rating=100*(rating-min(rating))/(max(rating)-min(rating)))




playerstat <- playerstat %>%  filter(!is.na(rating)) %>% group_by(attackerSteamID) %>%  summarize(name=last(name),rating=mean(rating),match_played=n())

oldplayers <- playerstat[order(playerstat$match_played, decreasing=TRUE), ] %>% top_n(5)

oldnames <- oldplayers$name   
```
```{r}
playerstat %>%  top_n(30,rating) %>% arrange(rating) %>% mutate(name = factor(name, levels = .$name)) %>% ggplot(., aes(rating, name)) +
        geom_point()+
  labs(title = "Top 30 players all time", x = "Rating",  y = "Name")

playerstat %>%  top_n(-30,rating) %>% arrange(rating) %>% mutate(name = factor(name, levels = .$name)) %>% ggplot(., aes(rating, name)) +
        geom_point()+
  labs(title = "Worst 30 players of all time", x = "Rating",  y = "Name")
```

```{r}
playerstat_time <- player_kills %>% inner_join(player_damages) %>% inner_join(player_flashes) %>%  inner_join(player_grenades)  %>% mutate(rating=100*(coef[1]+kpr*coef[2]+adr*coef[3]+first_kill_percent*coef[4]+grenades_per_round *coef[5]+attack_grenades_round*coef[6]+assist_percent*coef[8]+non_traded_percent*coef[9]+avg_flash_duration *coef[10]))

playerstat_time <- playerstat_time %>% mutate(rating=100*(rating-min(rating))/(max(rating)-min(rating)))
playerstat_time <- playerstat_time %>% group_by(event,attackerSteamID) %>%  summarize(name=last(name),rating=mean(rating),match_played=n(),event=last(event),date=last(date))



playerstat_time <- playerstat_time %>% filter(name %in% oldnames) 

```



```{r}
level_order <- c('DreamHack Winter 2013','EMS One Katowice 2014','ESL One Cologne 2014','DreamHack Winter 2014','ESL One Katowice 2015','ESL One Cologne 2015','DreamHack Open Cluj-Napoca 2015','MLG Columbus 2016','ESL One Cologne 2016','ELEAGUE Major 2017','PGL Major Krakow 2017','ELEAGUE Major 2018','FACEIT Major 2018','IEM Katowice 2019','StarLadder Major Berlin 2019')

ggplot(playerstat_time, aes(x = factor(event, level = level_order), y = rating, group=name, col=name))+ 
geom_line() + geom_point()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
#heatmpas



library(ggpubr)
library(jpeg)

img <- readJPEG("code/maps/de_mirage_light.jpg")



heat_kills <- damages %>%  filter(map_name == "de_mirage") %>% filter(match_event=="StarLadder Major Berlin 2019" )
# Area + contour
ggplot(heat_kills, aes(x=attackerX, y=attackerY) )+
background_image(img) +
#geom_point(alpha=0.2,color="red")+
stat_density_2d(aes(fill = log10(..level..)), geom = "polygon",alpha=0.6,h=294.1)+ scale_fill_continuous(type = "viridis")+
  xlim(-3050, 1700)+
  ylim(-3200,1520) + theme(aspect.ratio=1)



```
```{r}

heat_kills <- damages %>%  filter(map_name == "de_mirage" ) %>% filter(attackerSteamID==76561198034202275) %>% filter(weapon=="AWP") %>% filter(attackerSide =="CT"
)

# Area + contour
ggplot(heat_kills, aes(x=victimX, y=victimY) )+
background_image(img) +
#geom_point(alpha=0.2,color="red")+
stat_density_2d(aes(fill = log10(..level..)), geom = "polygon",alpha=0.6,h=294.1)+ scale_fill_continuous(type = "viridis")+
  xlim(-3050, 1700)+
  ylim(-3200,1520) + theme(aspect.ratio=1)

heat_kills <- damages %>%  filter(map_name == "de_mirage" ) %>% filter(attackerSteamID==76561198034202275) %>% filter(weapon=="AWP") %>% filter(attackerSide =="T"
)

# Area + contour
ggplot(heat_kills, aes(x=victimX, y=victimY) )+
background_image(img) +
#geom_point(alpha=0.2,color="red")+
stat_density_2d(aes(fill = log10(..level..)), geom = "polygon",alpha=0.6,h=294.1)+ scale_fill_continuous(type = "viridis")+
  xlim(-3050, 1700)+
  ylim(-3200,1520) + theme(aspect.ratio=1)
# SIMPLE's damages with the AWP weapon




heat_kills <- damages %>%  filter(map_name == "de_mirage" ) %>%  filter(weapon=="AWP") %>% filter(attackerSide =="CT")

ggplot(heat_kills, aes(x=victimX, y=victimY) )+
background_image(img) +
#geom_point(alpha=0.2,color="red")+
stat_density_2d(aes(fill = log10(..level..)), geom = "polygon",alpha=0.6,h=294.1)+ scale_fill_continuous(type = "viridis")+
  geom_segment(aes(xend=attackerX, yend=attackerY),alpha=0.05)+
  xlim(-3050, 1700)+
  ylim(-3200,1520) + theme(aspect.ratio=1)
# amages with the AWP weapon




```
```{r}
ggplot(heat_kills, aes(x=attackerX, y=attackerY) )+
background_image(img) +
#geom_point(alpha=0.2,color="red")+
stat_density_2d(aes(fill = log10(..level..)), geom = "polygon",alpha=0.6,h=400)+ scale_fill_continuous(type = "viridis")+
    geom_segment(aes(xend=victimX, yend=victimY),alpha=0.05)+
  xlim(-3050, 1700)+
  ylim(-3200,1520) + theme(aspect.ratio=1)
# amages with the AWP weapon


heat_kills <- damages %>%  filter(map_name == "de_mirage" ) %>%  filter(weapon=="M4A4") %>% filter(attackerSide =="CT")

ggplot(heat_kills, aes(x=attackerX, y=attackerY) )+
background_image(img) +
#geom_point(alpha=0.2,color="red")+
stat_density_2d(aes(fill = log10(..level..)), geom = "polygon",alpha=0.6,h=250)+ scale_fill_continuous(type = "viridis")+
    geom_segment(aes(xend=victimX, yend=victimY),alpha=0.01)+
  xlim(-3050, 1700)+
  ylim(-3200,1520) + theme(aspect.ratio=1)
# amages with the AWP weapon
```












```{r}

wins <- kills %>%  filter(attackerTeam!=victimTeam) %>%  group_by(match_id,round_num) %>%  summarise(map=last(map_name),winner=last(round_won_by),T_team=last(if_else(attackerSide=="T",attackerTeam,victimTeam)),event=last(match_event),map=last(map_name))
wins <- wins %>% mutate(win_side=if_else(winner==T_team,'T','CT'))

global_wins <- wins %>% group_by(event) %>% summarise(event=last(event),tot=n(),T_percent=100*sum(win_side=='T')/n()) %>% mutate(CT_percent=100-T_percent)


level_order <- c('DreamHack Winter 2013','EMS One Katowice 2014','ESL One Cologne 2014','DreamHack Winter 2014','ESL One Katowice 2015','ESL One Cologne 2015','DreamHack Open Cluj-Napoca 2015','MLG Columbus 2016','ESL One Cologne 2016','ELEAGUE Major 2017','PGL Major Krakow 2017','ELEAGUE Major 2018','FACEIT Major 2018','IEM Katowice 2019','StarLadder Major Berlin 2019')


library(reshape2)
gloabl_wins_melt <- melt(global_wins,  variable.name="var",id.vars=c("event","tot"))

ggplot(gloabl_wins_melt, aes(x = factor(event, level = level_order), y = value, group=var, col=var))+ 
geom_line() + geom_point()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```
```{r fig.height=7,fig.width=15}
map_wins <- wins %>% group_by(event,map) %>% summarise(event=last(event),tot=n(),T_percent=100*sum(win_side=='T')/n()) %>% mutate(CT_percent=100-T_percent)


map_wins_melt <- melt(map_wins,  variable.name="var",id.vars=c("event","tot","map"))

ggplot(map_wins_melt, aes(x = factor(event, level = level_order), y = value, group=var, col=var))+ 
facet_wrap(~map)+
geom_line() + geom_point()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```
```{r fig.height=10,fig.width=8}
level_order <- c('DreamHack Winter 2013','EMS One Katowice 2014','ESL One Cologne 2014','DreamHack Winter 2014','ESL One Katowice 2015','ESL One Cologne 2015','DreamHack Open Cluj-Napoca 2015','MLG Columbus 2016','ESL One Cologne 2016','ELEAGUE Major 2017','PGL Major Krakow 2017','ELEAGUE Major 2018','FACEIT Major 2018','IEM Katowice 2019','StarLadder Major Berlin 2019')


weapon_usage <- damages %>% group_by(match_id,attackerSteamID,weapon,round_num) %>% summarize(weapon=last(weapon),date=last(match_date),event=last(match_event),side=last(attackerSide),name=last(attackerName))


weapon_usage <- weapon_usage %>% group_by(event,weapon) %>% summarize(weapon=last(weapon),weapon_usage=n(),date=last(date),event=last(event),side=last(side))
#tot_count <- weapon_usage %>%  group_by(event) %>% summarize(tot_usage=sum(weapon_usage))
tot_count <- weapon_usage %>%  group_by(event) %>% summarize(tot_usage=sum(weapon_usage))
weapon_usage <- weapon_usage %>% inner_join(tot_count) %>%  mutate(weapon_percent=weapon_usage/tot_usage)


weapon_list <- c("UMP-45",'MAC-10','MP7','MP9','P90')
a <-  ggplot(weapon_usage %>% filter( (weapon %in% weapon_list)), aes(x = factor(event, level = level_order), y = weapon_percent, group=weapon, col=weapon))+ 
geom_line() + geom_point()+ theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

weapon_list <- c("CZ75 Auto",'Desert Eagle','Five-SeveN','p250','Tec-9')
b <- ggplot(weapon_usage %>% filter( (weapon %in% weapon_list)), aes(x = factor(event, level = level_order), y = weapon_percent, group=weapon, col=weapon))+ 
geom_line() + geom_point()+ theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

weapon_list <- c("AK-47",'SG 553','AUG','M4A4','M4A1')
c <- ggplot(weapon_usage %>% filter( (weapon %in% weapon_list)), aes(x = factor(event, level = level_order), y = weapon_percent, group=weapon, col=weapon))+ 
geom_line() + geom_point()+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



library(patchwork)
(a/b/c)



```

```{r,fig.height=6,fig.width=13}
library(dplyr)
library(ggplot2)
library(openintro)
library(tidyverse)
library(ggplot2)
library(ggmosaic)
library(mosaic)
library(vcd)
library(lubridate)
library(jsonlite)
library(plotly)
library(parcoords)
library(easyalluvial)
library(patchwork)
names <- c("device","dupreeh","Xyp9x","Magisk","gla1ve")

players <- kills %>% group_by(match_event,attackerSteamID)   %>%  summarise(name=last(attackerName),team=last(attackerTeam),date=last(match_date) )
players <- filter(players, name %in% names)

#players <- players %>% group_by(team,name) %>% summarise(name=last(name),team=last(team),date=last(date), count = n() , event = last(match_event),attackerSteamID=last(attackerSteamID))



level_order <- c('EMS One Katowice 2014','ESL One Cologne 2014','DreamHack Winter 2014','ESL One Katowice 2015','ESL One Cologne 2015','DreamHack Open Cluj-Napoca 2015','MLG Columbus 2016','ESL One Cologne 2016','ELEAGUE Major 2017','PGL Major Krakow 2017','ELEAGUE Major 2018','FACEIT Major 2018','IEM Katowice 2019','StarLadder Major Berlin 2019')
#players <- players[match(level_order, players$match_event),]
players <- players[order(factor(players$match_event, levels=unique(level_order))),]

alluvial_long(players
              , key = match_event
              , value = team
              , id = attackerSteamID
              , fill = name
              , fill_right = F
              , NA_label = 'None'
              ,order_levels_key =level_order
              ,col_vector_value = c("blue","black","green","yellow","red")
              )
```


```{r}
#uncomment to install ggbiplot

#library(cli)
#library(devtools)

#install_github("vqv/ggbiplot")
```
PCA

```{r}
pca.variables <- c('kills_tot', 'kpr', 'hs_percent', 'blinded_percent', 'first_kill_percent',
'non_traded_percent', 'assist_percent', 'strafing', 'adr',  'avg_flash_duration', 'grenades_per_round')

team_killsstat.pca <- prcomp(team_killsstat[,pca.variables], center = TRUE,scale. = TRUE)

#summary(team_killsstat.pca)
team_killsstat <- team_killsstat %>% mutate(won=if_else(relative_score_diff>0,TRUE,FALSE))
```



We now color points so that teams that have won appear in a certain color, and teams that didn't appear in another color. We also make arrow stand out a bit more, and add the correlation circle.

```{r fig.height = 8}
library(ggbiplot)
ggbiplot(team_killsstat.pca , obs.scale = 1, var.scale =1,circle=TRUE, group=team_killsstat$won,varname.adjust = 1.7, varname.size = 2.3,  alpha = 0.2)+ xlim(-4.5, 3) + 
  ylim(-3.1, 5) +
  ggtitle("PCA of team statistics in matches")  +
  theme(plot.title = element_text(hjust = 0.5))+
  labs(colour = "Match won")



```