# Conclusion

The massive amount of data at our disposal means that we had to severely restrain the subset of information used for analysis.
We only used 1.3% of the data (1GB/80GB). Considering the reduced amount of data used we still managed to get interesting information from the 400+ matches. 

With data covering 5 years from 2015 to 2019, we managed to generate a global rating to measure the performance of teams and players (5.1-5.3). The game data was also used to get insights into the team's play styles and habits (5.4 and 6). We also showed the game's balance evolution throughout the years (5.5). 

That being said, there is still a lot to analyze with the rest of the data that was unused. For example, we did not cover the economic aspect of the game: different weapon buying decisions from the players can impact the rest of the game. 

Sill, the D3 interactive part (chapter 6) allowed us to show more than regular static graphs would allow.

Also while we had a look at players' positions in a match, a more precise round-by-round analysis can get more information on specific team strategies. However, this would have necessitated players' position at frequent intervals which would increase the data size by a considerable margin.

With e-sport organizations becoming more professional with dedicated game analysts working for the players, there have been several tools [1],[2],[3] that have been created to better analyze and visualize game data. 

It would also be interesting to have a look at casual players' data to see how they differ from pro players. The fact that game developers already use machine learning to detect online cheaters in game means that there is still a lot to be explored.

Overall, exploring the topic of game data analysis was very interesting and we learned a lot about R graphs creation and interactive graphs with D3. 


[1] [leetify](https://leetify.com/)

[2] [scope.gg](https://scope.gg/)

[3] [noesis.gg](https://www.noesis.gg/)